### PR TITLE
Adding Issues Templates for Contributor

### LINKED ISSUE #33: Templates for contributing
Adding templates for open source contributions like bug report, new issue suggestion helps in making issues regular and easy to track.

Could you assign this issue to me under hacktoberfest - accepted and gssoc 24-exrd. Thanks

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #33 I'have created a 3 types of issues templates 
1. BUG-Report
2. Feat-Report
3. Custom-Report

Now for every contributor he/she wants to create an issue then it have 3 choices of issues.

@BamaCharanChhandogi Please review it and merge with labels:)

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@BamaCharanChhandogi ??

**Comment by shreya-paul-17** [comment]
@sanjay-kv @MastanSayyad please review it

**Review by MastanSayyad — COMMENTED** [review]
@BamaCharanChhandogi Program manager this side, .md/markdown/docs/workflows changes can only have level 1 no matter how many files or how many lines have changes

Please reduce the levels fromlevel 2 to level 1

also please add me as a collaborator, we are currently reviewing the lederboard so we need access to the projects to change the levels

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi Program manager this side, .md/markdown/docs/workflows changes can only have level 1 no matter how many files or how many lines have changes
> 
> Please reduce the levels fromlevel 2 to level 1
> 
> also please add me as a collaborator, we are currently reviewing the lederboard so we need access to the projects to change the levels

ok

**Pull request merged**
