### PR TITLE
Added feature Scroll to Top of Website

### PR DESCRIPTION
**Pull request by Ishika-Gupta06**
A floating button styled with TailwindCSS classes that scrolls to the top of the page when clicked.
This scroll-to-top button will appear only when the user scrolls down, creating a smooth UX for navigation!

### CODE REVIEW

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM, thanks.

**Comment by Ishika-Gupta06** [comment]
@BamaCharanChhandogi please add the label hacktoberfest!!

**Comment by Ishika-Gupta06** [comment]
@BamaCharanChhandogi  please add the label hacktoberfest!

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi please add the label hacktoberfest!

I have alredy `Hacktoberfest` tagin my project. If I do not add it here(PR/issue), it will still count in `Hacktoberfest`.

**Pull request merged**
