### PR TITLE
Solved issue #49

### PR DESCRIPTION
**Pull request by manikdamle**
Added dropdown list to display common Programming languages

### CODE REVIEW

**Comment by manikdamle** [comment]
@BamaCharanChhandogi pls review

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Users can select multiple languages. So add multiple options.

**Comment by manikdamle** [comment]
Ok will do that

**Comment by manikdamle** [comment]
Hey @BamaCharanChhandogi! I've made the necessary changes. Pls review

**Comment by BamaCharanChhandogi** [comment]
> Hey @BamaCharanChhandogi! I've made the necessary changes. Pls review

I think you do not understand what I was trying to say, look at this design 

image

apply this design and add also `other` fields where users can write the language.

**Comment by manikdamle** [comment]
Oh ok got it

**Comment by manikdamle** [comment]
@BamaCharanChhandogi Pls check

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Need a little bit of correction.

- why is this submit button?

image

- all list has to be put inside a drop-down menu. 

image

- As I said before, the `other` option should be available:- when the user clicks on the `other` option an input box will open the user can write their language.

**Comment by manikdamle** [comment]
Ok I got it. I'll do it

**Comment by manikdamle** [comment]
@BamaCharanChhandogi pls check now

**Review by BamaCharanChhandogi — COMMENTED** [review]
I am testing locally. I can see your code is not working at all and is giving errors a lot. 
You can do one thing: raise a new PR with an updated code base.

**Comment by manikdamle** [comment]
ok

**Pull request closed without merging**
