### PR TITLE
Feature : Implemented an interactive FAQ section on the homepage for …

### PR DESCRIPTION
**Pull request by rajgharat07**
…improved user engagement and accessibility.

# Description

- Added a new FAQ section to the homepage to address common user queries and enhance the overall user experience.
- The FAQ section is fully interactive, allowing users to expand and collapse individual questions for ease of navigation.
- Used responsive design techniques to ensure seamless functionality across different devices and screen sizes.
- FAQ data is dynamically rendered, making future updates easy and scalable.

## Fixes issue #77

### CODE REVIEW

**Comment by rajgharat07** [comment]
Hi @BamaCharanChhandogi, could you kindly review this PR when you have a moment? Your feedback would be much appreciated!

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
I just wanted to say that looks good, thanks. 
It would be better if we added a dedicated FAQ page and a button in the navbar of the FAQ page. What do you think?

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Add a FAQ button onthe  Navbar.

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM,thanks.

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
