### PR TITLE
added chatbot for enhanced user experience

### LINKED ISSUE #105: [Feature]: Integrate a Chatbot for Instant User Support
# 🚀 Feature Request

### 📝 Feature Description

Enhance the website's user experience by integrating a chatbot that provides instant answers to user inquiries. The chatbot should be easily accessible, provide relevant responses, and offer seamless assistance for common queries, improving user engagement and support.

@aswathcm29 please assign this to me under gssoc-ext and hacktoberfest

### 🔧 How Will This Enhance the App?

Add a chatbot icon or button that floats on the bottom-right corner of the site.
When clicked, the chatbot window should expand with a smooth animation, displaying an input field and previous chat history.

The chatbot should respond to frequently asked questions (related to the FAQ section) and common inquiries about products or services.
Implement a fallback response for questions outside the chatbot's scope (e.g., "Sorry, I don't have an answer for that. Please contact our support team.").

### 📸 Additional Context

 please assign this to me under gssoc-ext and hacktoberfest

### PR DESCRIPTION
**Pull request by sezallagwal**
closes #105 

https://github.com/user-attachments/assets/4a6b1910-e9a7-4db9-b982-dcaf63b3f1ba

please review this pr @BamaCharanChhandogi 
Thanks!

### CODE REVIEW

**Review by BamaCharanChhandogi — COMMENTED** [review]
It looks really good, thanks. But one question: you all have bot access. So, is there any option to transfer ownership? In the future, if I want to add or update anything, I can update it.

**Comment by sezallagwal** [comment]
@BamaCharanChhandogi The chatbot is built and managed using Chatbase, and the ownership is tied to the original creator's account. While I can’t directly transfer ownership, I'm more than happy to collaborate on updates or changes whenever needed.

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi The chatbot is built and managed using Chatbase, and the ownership is tied to the original creator's account. While I can’t directly transfer ownership, I'm more than happy to collaborate on updates or changes whenever needed.

That's okay. I noticed recently that you don't have a GitHub profile, so you can use this project to help you create one.

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM, thanks.

**Comment by sezallagwal** [comment]
@BamaCharanChhandogi I appreciate the suggestion! I’ve been working on adding more projects, so I’ll definitely keep that in mind. Always open to ideas if you have any!

**Pull request merged**
