### PR TITLE
Issue #82 : Add Stack Selection and Pre-Fill Options with Enhanced UI in InputForm Component

### PR DESCRIPTION
**Pull request by MonilMehta**
Added new stack selection and pre-fill options in the `InputForm` component, along with significant UI improvements for better user experience.

### Changes:
- **Stack Selection**:
  - Implemented a dropdown for users to select from predefined project stacks (Python, MERN, Django, React).
  - Dynamically updates the form based on the selected stack.

- **Pre-Fill Feature**:
  - Added a "Pre-fill" button that populates the form fields (name, description, features, etc.) with template data for the selected stack.
  - Allows users to quickly start with pre-defined content and edit as needed.

- **UI Enhancements**:
  - Styled the stack selection dropdown with a modern look, including focus rings, hover effects, and smooth transitions.
  - Integrated responsive design and accessibility improvements, such as enhanced focus states and placeholder text styling.

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Hi @MonilMehta, 
thanks for raising this. but I think when the user uses the `prefill` button, only the `installation` part remains the same user doesn't need all section sample codes because the user will enter details their project details.

**Comment by MonilMehta** [comment]
Alright, if you have any improvement in mind, I'll be happy to work on it.

Regards,
Monil Mehta

**Comment by MonilMehta** [comment]
Alright thanks, will do that and submit another PR.

Regards,
Monil Mehta

**Comment by MonilMehta** [comment]
As per  your suggestion, added Pre-fill option for installation and contributions.

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Could you change the dropdown color? It's not visible. 

image

**Comment by MonilMehta** [comment]
image
My bad, its rendering correctly on my device, I'll look into it

**Comment by MonilMehta** [comment]
Changed text color, please check again.

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
