### PR TITLE
Added feature : Emoji Picker and GIF/Image Picker

### PR DESCRIPTION
**Pull request by Siddhisony**
- Added functionality for emoji support in text input fields. When user hover their cursor, the emoji changes
- Implemented Image/GIF URL input functionality.

image

### CODE REVIEW

**Review by BamaCharanChhandogi — COMMENTED** [review]
You have done great. But one thing you have added image or gif, what is the purpose of it?

**Comment by Siddhisony** [comment]
> You have done great. But one thing you have added image or gif, what is the purpose of it?

Thank you. I have added this so that user can add an image in their README just like I have did.

**Comment by Siddhisony** [comment]
Kindly merge my commit or let me know if there are changes required.

**Comment by Siddhisony** [comment]
> You have just added and stored an image, but you have to send it to Gemini so that it can be added to the readme profile.



> You have just added and stored an image, but you have to send it to Gemini so that it can be added to the readme profile.

Thank you for your feedback! I realize now that I'm not entirely sure how to integrate the image feature with Gemini to update the README profile. Would it be alright if I remove the image/GIF feature for now and just keep the emoji picker functionality?

**Comment by BamaCharanChhandogi** [comment]
> > You have just added and stored an image, but you have to send it to Gemini so that it can be added to the readme profile.
> 
> > You have just added and stored an image, but you have to send it to Gemini so that it can be added to the readme profile.
> 
> Thank you for your feedback! I realize now that I'm not entirely sure how to integrate the image feature with Gemini to update the README profile. Would it be alright if I remove the image/GIF feature for now and just keep the emoji picker functionality?

yes, you can

**Pull request merged**
