### PR TITLE
added star and fork feature #68

### PR DESCRIPTION
**Pull request by c4dr-me**
Added star and fork buttons fetching data from github API of the repository
Issue: #68

https://github.com/user-attachments/assets/ce373cf4-67b1-4403-bd4a-442c6ecb5f4d

### CODE REVIEW

**Comment by c4dr-me** [comment]
@BamaCharanChhandogi can u review the pr.
thanks! and can u add hacktober label as well

**Comment by BamaCharanChhandogi** [comment]
we have already a GitHub button, so I do not think these buttons are needed. What do you think?

**Comment by c4dr-me** [comment]
> we have already a GitHub button, so I do not think these buttons are needed. What do you think?

Since its an open source project I think its good to show the no. of star and fork feature making it easy for people to contribute directly by clicking those button when they access website. It is much more appealing and User friendly in that respect

**Comment by BamaCharanChhandogi** [comment]
> > we have already a GitHub button, so I do not think these buttons are needed. What do you think?
> 
> Since its an open source project I think its good to show the no. of star and fork feature making it easy for people to contribute directly by clicking those button when they access website. It is much more appealing and User friendly in that respect. And as the project gains popularity it will look good for the website

can you do this type of design?

image

**Comment by c4dr-me** [comment]
> > > we have already a GitHub button, so I do not think these buttons are needed. What do you think?
> > 
> > 
> > Since its an open source project I think its good to show the no. of star and fork feature making it easy for people to contribute directly by clicking those button when they access website. It is much more appealing and User friendly in that respect. And as the project gains popularity it will look good for the website
> 
> can you do this type of design?
> 
> image

so only for the star one ?

**Comment by c4dr-me** [comment]
image
@BamaCharanChhandogi something like this?

**Comment by BamaCharanChhandogi** [comment]
> image @BamaCharanChhandogi something like this?

you can keep only stars. Remove the GitHub icon from the navbar and add stars there.

**Comment by c4dr-me** [comment]
image
@BamaCharanChhandogi does this look good?

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
It looks good, but it's showing, merge conflicts, I request you to do the same with the updated code. I mean raise a new pr or update the latest in this PR.

**Pull request closed without merging**
