### PR TITLE
Update App.jsx

### PR DESCRIPTION
**Pull request by devanshar**
No more Unnecessary renders and added lazy loading

### CODE REVIEW

**Review by BamaCharanChhandogi — COMMENTED** [review]
Hi @devanshar, 
Could you tell me or provide an example of where this component is rendering unnecessarily?

**Comment by devanshar** [comment]
> Hi @devanshar, Could you tell me or provide an example of where this component is rendering unnecessarily?

When using NavLink, React re-renders components even if the active state doesn't change, due to the className function recalculating on every render.

**Comment by devanshar** [comment]
Every time the App component renders (due to state updates or other reasons), both Home and GitHubProfileGenerator components will re-render even if their props haven't changed.
The inline className function for NavLink recalculates on every render, leading to unnecessary re-renders of the navigation links as well.

=> used React.memo to wrap the Home and GitHubProfileGenerator components.
Now, it  will only re-render these components if their props change. If their props remain the same between renders they will not re-render.

Now home and profile generator only render for the first time

**Review by BamaCharanChhandogi — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
