### PR TITLE
Feat: Adding CI-CD workflow for READMEasy repo

### LINKED ISSUE #95: [Custom]: CI-CD Workflow
# 💡 Custom Issue

### 📝 Description
There is no CI-CD Workflow in this repo.

What CI-CD did??
A CI/CD workflow on GitHub automates the process of building, testing, and deploying code. When changes are pushed to the repository, GitHub Actions triggers the workflow, starting with building the code, running tests, and performing quality checks. If the tests pass, the code can be deployed to a staging or production environment. Notifications are sent to inform stakeholders about the workflow's success or failure.

### 🔍 Steps to Reproduce (if applicable)
1. Go to .github folder  
2. Make separate file for CI-CD workflow

### 🎯 Expected Outcome
When user try to create a PR then it run and check first all test case.

@BamaCharanChhandogi Please assign this issue to me under gssoc-ext, level-2,3:)

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #95 
Adding CI-CD Workflow for READMEasy repo.
Now it will run and deploy for every PR and show its corresponding output.

@BamaCharanChhandogi Please review my PR and merge with labels:)

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@BamaCharanChhandogi Please review my PR and merge with labels:)

**Comment by harshbhar0629** [comment]
@BamaCharanChhandogi Please review:)

**Comment by harshbhar0629** [comment]
@BamaCharanChhandogi please review

**Comment by harshbhar0629** [comment]
@BamaCharanChhandogi ...??????

**Comment by harshbhar0629** [comment]
@BamaCharanChhandogi Please review:)
@BamaCharanChhandogi Please review:)

**Comment by harshbhar0629** [comment]
@BamaCharanChhandogi Please review:)

**Comment by BamaCharanChhandogi** [comment]
Do not need at this time.

**Pull request closed without merging**
