### PR TITLE
Added feature : Emoji Picker

### PR DESCRIPTION
**Pull request by Siddhisony**
- Added functionality for emoji support in text input fields. When user hover their cursor, the emoji changes.

Screenshot 2024-11-11 130658

### CODE REVIEW

**Comment by Siddhisony** [comment]
Kindly review this @BamaCharanChhandogi

**Review by BamaCharanChhandogi — APPROVED** [review]
please resolve the merge conflicts, then I can merge.

**Comment by Siddhisony** [comment]
Done

**Comment by Siddhisony** [comment]
I have resolved the conflicts

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
